### PR TITLE
Updated english language pack and post notification links

### PR DESCRIPTION
**Pull request by therealsujitk**
In these commits, I have fixed the grammatical errors in 04acecc and changed the post notification links in 03b7426 such that it leads directly to the post instead of the discussion page. Please verify these commits as I have NOT tested it.

### CODE REVIEW

**Comment by hrvoje-hr** [comment]
@therealsujitk, unfortunately, it's still the same at me

**Comment by therealsujitk** [comment]
@hrvoje-hr, it should work this time. Can you tell me how you are testing it?

**Comment by hrvoje-hr** [comment]
@therealsujitk code from old file is replaced with the code from the new file, then I clear cache.

I would test the new code, but you didn't updated it yet.

**Comment by therealsujitk** [comment]
@hrvoje-hr, what about the language pack? Does it work as per the changes?

**Comment by hrvoje-hr** [comment]
@therealsujitk just checked it, Yes, it works fine with translation.

**Comment by hrvoje-hr** [comment]
Just to be clear, only translation is working.

**Comment by therealsujitk** [comment]
@hrvoje-hr, yes got it. @NikoVonLas, only 04acecc is working properly so it can be merged. Please **DO NOT** merge 03b7426. I will submit a separate pull request with the second file fully functional when I get some time.

**Comment by therealsujitk** [comment]
@NikoVonLas, Please verify the commits 04acecc and 9a3af89 and consider merging them to your branch. 04acecc has been tested and will work properly. 9a3af89 will also work properly but will not navigate to posts at the moment as explained in the post on [flarum](https://discuss.flarum.org/d/22573-how-to-navigate-to-a-particular-post-in-flarum/6) by @clarkwinkelmann. He has opened an issue [here](https://github.com/flarum/core/issues/1972) for the same to be resolved.

**Comment by NikoVonLas** [comment]
Thank you )
I just merge it, and i can make correct links on frontend. Only until the problem with backend links is solved. What do you think? Its good practice?

**Comment by therealsujitk** [comment]
@NikoVonLas Yes, I think that's a good idea.
While updating SendWebPushNotifications.php I may have removed some arguments in the $attrs for the english language pack, I didn't realise this could affect the russian language pack. Would you like me to fix that?

**Comment by NikoVonLas** [comment]
@therealsujitk Yes please )

**Pull request merged**
